In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\pmls\appdata\local\programs\python\python313\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pmls\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pmls\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\pmls\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\pmls\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

In [2]:
numbers = pd.Series([1, 2, 3, 4, 5])

numbers

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
print(numbers.dtype)
print(numbers.index)
numbers.values

int64
RangeIndex(start=0, stop=5, step=1)

array([1, 2, 3, 4, 5])

In [4]:
#indexing
print(numbers[3])
numbers[0:4]

4

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
#location based indexing(iloc)
print(numbers.loc[3])
print(numbers.iloc[0:4])
print(numbers.iloc[[1,2,4]])

4
0    1
1    2
2    3
3    4
dtype: int64
1    2
2    3
4    5
dtype: int64

In [6]:
fruits = ["Apple","Banana", "Mango", "Orange", "Grapes"]
numbers.fruits = fruits
numbers

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
#loc -----> Label based indexing
print(numbers.loc[3])
# In label based indexing both the start and end values are included

4

In [7]:
#Dictionary
fruits_Protiens = {
    "Apple" : 2.0,
    "Banana" : 1.5,
    "Orange" : 1.0,
    "Grape" : 2.5,
    "Guava" : 3.0,

}
s = pd.Series(fruits_Protiens)
s

Apple     2.0
Banana    1.5
Orange    1.0
Grape     2.5
Guava     3.0
dtype: float64

In [8]:
#Conditional Selection
print(s>1)
#print(s[s>1])

Apple      True
Banana     True
Orange    False
Grape      True
Guava      True
dtype: bool

In [9]:
# Logical Operators ----> and, or, not
print([(s<2) & (s>0.5)])
print([~(s<2)])

[Apple     False
Banana     True
Orange     True
Grape     False
Guava     False
dtype: bool]
[Apple      True
Banana    False
Orange    False
Grape      True
Guava      True
dtype: bool]

In [10]:
s

Apple     2.0
Banana    1.5
Orange    1.0
Grape     2.5
Guava     3.0
dtype: float64

In [11]:
# Modifyinf the values of a series
s["Apple"] = 4.5
s["Banana"] = 2.7
s["Orange"] = 1.2
s

Apple     4.5
Banana    2.7
Orange    1.2
Grape     2.5
Guava     3.0
dtype: float64

In [12]:
# Data Frames
data = {
    "Name": ["Bilal", "Ali", "Ahmed", "Hassan", "Hussain"],
    "Age" : [20, 21, 22, "NaN", 24],
    "Department" : ["CS", "IT", "IT", "CS", "IT"],
    "CGPA" : [3.5, 3.6, 3.7, 3.8, 3.9], 
    "Salary" : [50000, 60000, 70000, 80000, 90000]
}
data

{'Name': ['Bilal', 'Ali', 'Ahmed', 'Hassan', 'Hussain'],
 'Age': [20, 21, 22, 'NaN', 24],
 'Department': ['CS', 'IT', 'IT', 'CS', 'IT'],
 'CGPA': [3.5, 3.6, 3.7, 3.8, 3.9],
 'Salary': [50000, 60000, 70000, 80000, 90000]}

In [13]:
df = pd.DataFrame(data)
df

      Name  Age Department  CGPA  Salary
0    Bilal   20         CS   3.5   50000
1      Ali   21         IT   3.6   60000
2    Ahmed   22         IT   3.7   70000
3   Hassan  NaN         CS   3.8   80000
4  Hussain   24         IT   3.9   90000

In [14]:
df.head(2) #Show the first 2 rowa

    Name Age Department  CGPA  Salary
0  Bilal  20         CS   3.5   50000
1    Ali  21         IT   3.6   60000

In [15]:
df.tail(3) #Show the last 3 rowa

      Name  Age Department  CGPA  Salary
2    Ahmed   22         IT   3.7   70000
3   Hassan  NaN         CS   3.8   80000
4  Hussain   24         IT   3.9   90000

In [16]:
#loc and iloc
df.iloc[0:5]

      Name  Age Department  CGPA  Salary
0    Bilal   20         CS   3.5   50000
1      Ali   21         IT   3.6   60000
2    Ahmed   22         IT   3.7   70000
3   Hassan  NaN         CS   3.8   80000
4  Hussain   24         IT   3.9   90000

In [17]:
df.loc[0:1, ["Name", "Age"]] 
#In label based indexing both the start and end values are included

    Name Age
0  Bilal  20
1    Ali  21

In [18]:
df[["Age", "Department"]]

   Age Department
0   20         CS
1   21         IT
2   22         IT
3  NaN         CS
4   24         IT

In [19]:
df.drop("Age", axis=1)

      Name Department  CGPA  Salary
0    Bilal         CS   3.5   50000
1      Ali         IT   3.6   60000
2    Ahmed         IT   3.7   70000
3   Hassan         CS   3.8   80000
4  Hussain         IT   3.9   90000

In [20]:
df

      Name  Age Department  CGPA  Salary
0    Bilal   20         CS   3.5   50000
1      Ali   21         IT   3.6   60000
2    Ahmed   22         IT   3.7   70000
3   Hassan  NaN         CS   3.8   80000
4  Hussain   24         IT   3.9   90000

In [ ]:
# Inplace tell us to perfrom operation on original data frame 
# or not
# by default inplace is set to False
#if we set inplace to True then it will perform operation 
# on original data frame and remove the column from original 
# data frame

In [21]:
df["Age"] = df["Age"].replace("NaN", 23)
df

      Name Age Department  CGPA  Salary
0    Bilal  20         CS   3.5   50000
1      Ali  21         IT   3.6   60000
2    Ahmed  22         IT   3.7   70000
3   Hassan  23         CS   3.8   80000
4  Hussain  24         IT   3.9   90000

In [32]:
df.shape

(5, 5)

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      object
 2   Department  5 non-null      str
 3   CGPA        5 non-null      float64
 4   Salary      5 non-null      int64
dtypes: float64(1), int64(1), object(1), str(2)
memory usage: 368.0+ bytes

In [23]:
df.describe()

           CGPA        Salary
count  5.000000      5.000000
mean   3.700000  70000.000000
std    0.158114  15811.388301
min    3.500000  50000.000000
25%    3.600000  60000.000000
50%    3.700000  70000.000000
75%    3.800000  80000.000000
max    3.900000  90000.000000

In [24]:
# Broadcasting
df["Salary"] = df["Salary"] + 2000
df["Salary"]

0    52000
1    62000
2    72000
3    82000
4    92000
Name: Salary, dtype: int64

In [35]:
#Column Renaming
df.rename(columns={"Department" : "Dept"}, inplace=True)
df

      Name Age  Dept  CGPA  Salary
0    Bilal  20   NaN   3.5   52000
1      Ali  21   NaN   3.6   62000
2    Ahmed  22   NaN   3.7   72000
3   Hassan  23   NaN   3.8   82000
4  Hussain  24   NaN   3.9   92000

In [34]:
df["Dept"].unique()
df

      Name Age  Dept  CGPA  Salary
0    Bilal  20   NaN   3.5   52000
1      Ali  21   NaN   3.6   62000
2    Ahmed  22   NaN   3.7   72000
3   Hassan  23   NaN   3.8   82000
4  Hussain  24   NaN   3.9   92000