In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\pmls\appdata\local\programs\python\python313\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pmls\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pmls\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\pmls\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\pmls\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
numbers = pd.Series([1, 2, 3, 4, 5])

numbers

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [10]:
print(numbers.dtype)
print(numbers.index)
numbers.values

int64
RangeIndex(start=0, stop=5, step=1)

array([1, 2, 3, 4, 5])

In [18]:
#indexing
print(numbers[3])
numbers[0:4]

4

0    1
1    2
2    3
3    4
Name: My Numbers, dtype: int64

In [24]:
#location based indexing(iloc)
print(numbers.loc[3])
print(numbers.iloc[0:4])
print(numbers.iloc[[1,2,4]])

4
0    1
1    2
2    3
3    4
dtype: int64
1    2
2    3
4    5
dtype: int64

In [23]:
fruits = ["Apple","Banana", "Mango", "Orange", "Grapes"]
numbers.fruits = fruits
numbers

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
#loc -----> Label based indexing
print(numbers.loc[3])
# In label based indexing both the start and end values are included

4

In [7]:
#Dictionary
fruits_Protiens = {
    "Apple" : 2.0,
    "Banana" : 1.5,
    "Orange" : 1.0,
    "Grape" : 2.5,
    "Guava" : 3.0,

}
s = pd.Series(fruits_Protiens)
s

Apple     2.0
Banana    1.5
Orange    1.0
Grape     2.5
Guava     3.0
dtype: float64

In [14]:
#Conditional Selection
print(s>1)
#print(s[s>1])

Apple      True
Banana     True
Orange    False
Grape      True
Guava      True
dtype: bool

In [18]:
# Logical Operators ----> and, or, not
print([(s<2) & (s>0.5)])
print([~(s<2)])

[Apple     False
Banana     True
Orange     True
Grape     False
Guava     False
dtype: bool]
[Apple      True
Banana    False
Orange    False
Grape      True
Guava      True
dtype: bool]

In [19]:
s

Apple     2.0
Banana    1.5
Orange    1.0
Grape     2.5
Guava     3.0
dtype: float64

In [23]:
# Modifyinf the values of a series
s["Apple"] = 4.5
s["Banana"] = 2.7
s["Orange"] = 1.2
s

Apple     4.5
Banana    2.7
Orange    1.2
Grape     2.5
Guava     3.0
dtype: float64

In [24]:
# Data Frames
data = {
    "Name": ["Bilal", "Ali", "Ahmed", "Hassan", "Hussain"],
    "Age" : [20, 21, 22, 23, 24],
    "Department" : ["CS", "IT", "IT", "CS", "IT"],
    "CGPA" : [3.5, 3.6, 3.7, 3.8, 3.9]
}
data

{'Name': ['Bilal', 'Ali', 'Ahmed', 'Hassan', 'Hussain'],
 'Age': [20, 21, 22, 23, 24],
 'Department': ['CS', 'IT', 'IT', 'CS', 'IT'],
 'CGPA': [3.5, 3.6, 3.7, 3.8, 3.9]}

In [25]:
df = pd.DataFrame(data)
df

      Name  Age Department  CGPA
0    Bilal   20         CS   3.5
1      Ali   21         IT   3.6
2    Ahmed   22         IT   3.7
3   Hassan   23         CS   3.8
4  Hussain   24         IT   3.9

In [30]:
df.head(2) #Show the first 2 rowa

    Name  Age Department  CGPA
0  Bilal   20         CS   3.5
1    Ali   21         IT   3.6

In [29]:
df.tail(3) #Show the last 3 rowa

      Name  Age Department  CGPA
2    Ahmed   22         IT   3.7
3   Hassan   23         CS   3.8
4  Hussain   24         IT   3.9

In [31]:
#loc and iloc
df.iloc[0:3]

    Name  Age Department  CGPA
0  Bilal   20         CS   3.5
1    Ali   21         IT   3.6
2  Ahmed   22         IT   3.7